// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsGmjD5LU9qTK8gY9bHLS0RObEY4sQC0k',
    appId: '1:512785665284:web:1788e304ad124c9b511451',
    messagingSenderId: '512785665284',
    projectId: 'todo-51632',
    authDomain: 'todo-51632.firebaseapp.com',
    storageBucket: 'todo-51632.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-zTQkarezPz-Vi-o4ct0CygyjPKfEAc',
    appId: '1:512785665284:android:190c40f9f5c2c267511451',
    messagingSenderId: '512785665284',
    projectId: 'todo-51632',
    storageBucket: 'todo-51632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxDwWWjfQeHyX1LVAh5XkP_ut98kAsb8A',
    appId: '1:512785665284:ios:365d152d08bd24ba511451',
    messagingSenderId: '512785665284',
    projectId: 'todo-51632',
    storageBucket: 'todo-51632.firebasestorage.app',
    iosBundleId: 'io.github.alphapokedex.triviaBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxDwWWjfQeHyX1LVAh5XkP_ut98kAsb8A',
    appId: '1:512785665284:ios:365d152d08bd24ba511451',
    messagingSenderId: '512785665284',
    projectId: 'todo-51632',
    storageBucket: 'todo-51632.firebasestorage.app',
    iosBundleId: 'io.github.alphapokedex.triviaBase',
  );
}
